[package]
name = "deboa-h3"
version = "0.1.3-beta.1"
edition = "2021"
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
repository = "https://github.com/ararog/deboa-h3"
homepage = "https://github.com/ararog/deboa"
description = "H3 support for deboa"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["http", "networking", "client", "fetch", "rest-client"]
rust-version = "1.85.0"

[features]
default = []

[dependencies]
bytes = { version = "1.11" }
deboa = { path = "../deboa/deboa" }
#deboa = { version = "0.1.5-beta.1" }
h3 = { version = "0.0.8", default-features = false }
h3-quinn = { version = "0.0.10", default-features = false }
http = "1"
http-body-util = "0.1"
hyper-body-utils = { path = "../hyper-body-utils", features = ["h3"], default-features = false }
#hyper-body-utils = { version = "0.1.17", default-features = false }
